packages: []
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - vue-demi
ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
