http:
  port: 8599


# 百度定时推送 方便收绿
baidu:
  push: true
  url: https://www.keepon.online
  token: VzXKVoNrqnSAWINA

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  enable: false

minio:
  serverUrl: http://192.168.2.166:9000
  endpoint: 192.168.2.166:9000
  accessKeyID: tSvV3zWF8692PfCiUrlZ
  secretAccessKey: Z7dqowc5nHfYmhLglj6OyECNF98KM13x4k2XtviS
  useSSL: false
  bucketName: test

gitalk:
  enable: true
  clientID: '4b719059ee103950a239'
  clientSecret: 'b9d642cffab418205da3c8c1a0bf762a9d10817b'
  repo: 'gitalk'
  owner: 'keepon-online'
  admin:
    - 'keepon-online'
