version: "3.5"
services:
  site:
    image: jieepre/site:v1
    restart: always
    container_name: site
    working_dir: /app
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    environment:
      TZ: Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "8589:8589"
      - "8000:8000"
      - "8890:8890"

