version: "3.5"
services:
  site:
    image: ubuntu:22.04
    restart: always
    container_name: site
    working_dir: /app
    volumes:
      - ./site:/app/site:ro
      - ./config/config.yaml:/app/config/config.yaml
      - ./site.db:/app/site.db
      - ./ip2region.xdb:/app/ip2region.xdb
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./logs:/app/logs
    command: ./site
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
    ports:
      - "8589:8589"
      - "8000:8000"
      - "8890:8890"

