version: "3.5"
services:
  site:
    image: jieepre/site:v1
    restart: always
    container_name: site
    working_dir: /app
    volumes:
      - ./logs:/app/logs
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8589:8589"
      - "8000:8000"
      - "8890:8890"

